version: v1
logging:
    level: info
    format: console
coreum:
    client_key_name: iso20022-client
    grpc:
        url: https://full-node.testnet-1.coreum.dev:9090
    network:
        chain_id: coreum-testnet-1
        denom: utestcore
    contract:
        contract_address: testcore1eyky8vfdyz77zkh50zkrdw3mc9guyrfy45pd5ak9jpqgtgwgfvfqd8lkmc
        gas_adjustment: 1.4
        gas_price_adjustment: 1.2
        page_limit: 50
        out_of_gas_retry_delay: 500ms
        out_of_gas_retry_attempts: 5
        request_timeout: 10s
        tx_timeout: 1m0s
        tx_status_poll_interval: 500ms
processes:
    server:
        listen_address: :2843
    address_book:
        update_interval: 1m0s
        custom_repo_address: ""
    dtif:
        update_interval: 1m0s
        distributed_ledger: S87NJRT7T
        custom_source_address: ""
    queue:
        size: 50
        path: {{QUEUE_PATH}}
        status_cache_duration: 1h0m0s
    retry_delay: 10s
