name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          path: iso20022-client
          fetch-depth: 0
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push docker image
        run: |
          cd iso20022-client
          make push-docker
      - name: Build release artifacts 
        run: |
          mkdir ~/release-build
          cd iso20022-client
          make release BUILD_DIR=~/release-build
          sha256sum ~/release-build/* > ~/release-build/checksums.txt
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          generate_release_notes: true
          files: |
            /home/runner/release-build/*
