name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          path: iso20022-client
          fetch-depth: 0
      - name: Build binaries
        run: make build-all
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=release::true
          fi
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+-rc.*$ ]]; then
              echo ::set-output name=release_candidate::true
          fi
      - name: Link released binaries under right names
        run: |
          ln bin/artifacts/${{ github.sha }}/darwin_amd64/iso20022-client iso20022-client-darwin-amd64
          ln bin/artifacts/${{ github.sha }}/darwin_arm64/iso20022-client iso20022-client-darwin-arm64
          ln bin/artifacts/${{ github.sha }}/linux_amd64/iso20022-client iso20022-client-linux-amd64
          ln bin/artifacts/${{ github.sha }}/linux_arm64/iso20022-client iso20022-client-linux-arm64
          ln bin/artifacts/${{ github.sha }}/windows_amd64/iso20022-client iso20022-client-windows-amd64
          ln bin/artifacts/${{ github.sha }}/windows_arm64/iso20022-client iso20022-client-windows-arm64
      - name: Create release
        if: steps.check-tag.outputs.release == 'true'
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          files: |
            iso20022-client-darwin-amd64
            iso20022-client-darwin-arm64
            iso20022-client-linux-amd64
            iso20022-client-linux-arm64
            iso20022-client-windows-amd64
            iso20022-client-windows-arm64
      - name: Create release candidate
        if: steps.check-tag.outputs.release_candidate == 'true'
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          generate_release_notes: true
          files: |
            iso20022-client-darwin-amd64
            iso20022-client-darwin-arm64
            iso20022-client-linux-amd64
            iso20022-client-linux-arm64
            iso20022-client-windows-amd64
            iso20022-client-windows-arm64
